// Generated by Copilot - TrackPose pages

import 'package:dio/dio.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import '../config/app_config.dart';

class ApiClient {
  final Dio _dio;
  final FlutterSecureStorage _storage;

  ApiClient(this._dio, this._storage) {
    _dio.options.baseUrl = AppConfig.apiBaseUrl;
    _dio.options.connectTimeout = AppConfig.connectTimeout;
    _dio.options.receiveTimeout = AppConfig.apiTimeout;

    // Interceptor to add auth token
    _dio.interceptors.add(InterceptorsWrapper(
      onRequest: (options, handler) async {
        final token = await _storage.read(key: 'auth_token');
        if (token != null) {
          options.headers['Authorization'] = 'Bearer $token';
        }
        return handler.next(options);
      },
      onError: (error, handler) {
        // Handle common errors
        return handler.next(error);
      },
    ));
  }

  // Auth endpoints
  Future<Map<String, dynamic>> login(String email, String password) async {
    final response = await _dio.post('/auth/login', data: {
      'email': email,
      'password': password,
    });
    return response.data;
  }

  Future<Map<String, dynamic>> signup({
    required String fullName,
    required String email,
    required String password,
    required String role,
  }) async {
    final response = await _dio.post('/auth/signup', data: {
      'fullName': fullName,
      'email': email,
      'password': password,
      'role': role,
    });
    return response.data;
  }

  Future<Map<String, dynamic>> verifyEmail(String email, String code) async {
    final response = await _dio.post('/auth/verify-email', data: {
      'email': email,
      'code': code,
    });
    return response.data;
  }

  Future<void> resendVerification(String email) async {
    await _dio.post('/auth/resend-verification', data: {'email': email});
  }

  Future<void> forgotPassword(String email) async {
    await _dio.post('/auth/forgot-password', data: {'email': email});
  }

  Future<void> resetPassword(String token, String newPassword) async {
    await _dio.post('/auth/reset-password', data: {
      'token': token,
      'password': newPassword,
    });
  }

  // Facility endpoints
  Future<Map<String, dynamic>> createFacility({
    required String name,
    required String type,
  }) async {
    final response = await _dio.post('/facilities', data: {
      'name': name,
      'type': type,
    });
    return response.data;
  }

  // Subscription endpoints
  Future<Map<String, dynamic>> createTrialSubscription() async {
    final response = await _dio.post('/subscriptions/trial');
    return response.data;
  }

  Future<Map<String, dynamic>> checkout(String plan) async {
    final response = await _dio.post('/payments/checkout', data: {
      'plan': plan,
    });
    return response.data;
  }

  Future<Map<String, dynamic>> verifyPayment(String sessionId) async {
    final response = await _dio.post('/payments/verify', data: {
      'sessionId': sessionId,
    });
    return response.data;
  }

  Future<Map<String, dynamic>> verifyAccessCode(
      String facilityId, String code) async {
    final response = await _dio
        .post('/facilities/$facilityId/verify-code', data: {'code': code});
    return response.data;
  }

  // Profile endpoints
  Future<List<dynamic>> getProfiles() async {
    final response = await _dio.get('/profiles');
    return response.data;
  }

  // Admin endpoints
  Future<void> deleteAccount() async {
    await _dio.delete('/users/me');
  }
}

final storageProvider = Provider<FlutterSecureStorage>((ref) {
  return const FlutterSecureStorage();
});

final dioProvider = Provider<Dio>((ref) {
  return Dio();
});

final apiClientProvider = Provider<ApiClient>((ref) {
  final dio = ref.watch(dioProvider);
  final storage = ref.watch(storageProvider);
  return ApiClient(dio, storage);
});
