// Generated by Copilot - TrackPose pages

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'api_client_provider.dart';

class AuthState {
  final bool isAuthenticated;
  final bool isEmailVerified;
  final String? email;
  final String? role;
  final String? facilityId;
  final Map<String, dynamic>? user;
  final bool isLoading;
  final String? error;

  AuthState({
    this.isAuthenticated = false,
    this.isEmailVerified = false,
    this.email,
    this.role,
    this.facilityId,
    this.user,
    this.isLoading = false,
    this.error,
  });

  AuthState copyWith({
    bool? isAuthenticated,
    bool? isEmailVerified,
    String? email,
    String? role,
    String? facilityId,
    Map<String, dynamic>? user,
    bool? isLoading,
    String? error,
  }) {
    return AuthState(
      isAuthenticated: isAuthenticated ?? this.isAuthenticated,
      isEmailVerified: isEmailVerified ?? this.isEmailVerified,
      email: email ?? this.email,
      role: role ?? this.role,
      facilityId: facilityId ?? this.facilityId,
      user: user ?? this.user,
      isLoading: isLoading ?? this.isLoading,
      error: error,
    );
  }
}

class AuthNotifier extends StateNotifier<AuthState> {
  final ApiClient _apiClient;
  final FlutterSecureStorage _storage;

  AuthNotifier(this._apiClient, this._storage) : super(AuthState()) {
    _loadAuthState();
  }

  Future<void> _loadAuthState() async {
    final token = await _storage.read(key: 'auth_token');
    final email = await _storage.read(key: 'user_email');
    final role = await _storage.read(key: 'user_role');
    final isVerified = await _storage.read(key: 'email_verified');
    final facilityId = await _storage.read(key: 'facility_id');

    if (token != null) {
      state = state.copyWith(
        isAuthenticated: true,
        email: email,
        role: role,
        isEmailVerified: isVerified == 'true',
        facilityId: facilityId,
      );
    }
  }

  Future<void> login(String email, String password) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final response = await _apiClient.login(email, password);
      final token = response['token'] as String?;
      final userData = response['user'] as Map<String, dynamic>?;

      if (token != null) {
        await _storage.write(key: 'auth_token', value: token);
        await _storage.write(key: 'user_email', value: email);
        await _storage.write(
            key: 'user_role', value: userData?['role'] ?? 'PARENT');
        await _storage.write(
            key: 'email_verified',
            value: userData?['emailVerified']?.toString() ?? 'false');

        state = state.copyWith(
          isAuthenticated: true,
          email: email,
          role: userData?['role'],
          user: userData,
          isEmailVerified: userData?['emailVerified'] ?? false,
          isLoading: false,
        );
      }
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
      rethrow;
    }
  }

  Future<void> signup({
    required String fullName,
    required String email,
    required String password,
    String role = 'PARENT',
  }) async {
    print('📝 AUTH PROVIDER: Starting signup...');
    state = state.copyWith(isLoading: true, error: null);
    try {
      await _apiClient.signup(
        fullName: fullName,
        email: email,
        password: password,
        role: role,
      );

      print('💾 AUTH PROVIDER: Saving email and role to storage');
      await _storage.write(key: 'user_email', value: email);
      await _storage.write(key: 'user_role', value: role);

      print('✅ AUTH PROVIDER: Signup complete, updating state');
      state = state.copyWith(
        email: email,
        role: role,
        isLoading: false,
      );
      print('📊 AUTH PROVIDER: New state - email: $email, role: $role, isAuth: ${state.isAuthenticated}');
    } catch (e) {
      print('❌ AUTH PROVIDER ERROR: $e');
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
      rethrow;
    }
  }

  Future<void> verifyEmail(String code) async {
    state = state.copyWith(isLoading: true, error: null);
    try {
      final email = state.email ?? await _storage.read(key: 'user_email');
      if (email == null) throw Exception('Email not found');

      final response = await _apiClient.verifyEmail(email, code);
      final token = response['token'] as String?;

      if (token != null) {
        await _storage.write(key: 'auth_token', value: token);
        await _storage.write(key: 'email_verified', value: 'true');
      }

      state = state.copyWith(
        isAuthenticated: true,
        isEmailVerified: true,
        isLoading: false,
      );
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        error: e.toString(),
      );
      rethrow;
    }
  }

  Future<void> logout() async {
    await _storage.deleteAll();
    state = AuthState();
  }
}

final authProvider = StateNotifierProvider<AuthNotifier, AuthState>((ref) {
  final apiClient = ref.watch(apiClientProvider);
  final storage = ref.watch(storageProvider);
  return AuthNotifier(apiClient, storage);
});
