// Generated by Copilot - TrackPose pages

import 'package:flutter_riverpod/flutter_riverpod.dart';

// Mock profiles provider with seed data
final profilesProvider = Provider<List<Map<String, dynamic>>>((ref) {
  return [
    {
      'id': '1',
      'name': 'Emma Johnson',
      'age': 4,
      'avatarUrl': null,
      'moodSummary': {
        'dominant': 'happy',
        'score': 0.85,
        'trends': ['Engaged during playtime', 'Calm during rest'],
      },
    },
    {
      'id': '2',
      'name': 'Oliver Smith',
      'age': 6,
      'avatarUrl': null,
      'moodSummary': {
        'dominant': 'neutral',
        'score': 0.72,
        'trends': ['Focused on activities', 'Social interactions improving'],
      },
    },
  ];
});

// Mock KPIs for admin dashboard
final adminKpisProvider = Provider<Map<String, dynamic>>((ref) {
  return {
    'facilityMoodAverage': 0.78,
    'engagementByZone': {
      'Classroom A': 0.85,
      'Playground': 0.92,
      'Cafeteria': 0.68,
    },
    'staffPerformance': {
      'totalStaff': 12,
      'activeToday': 10,
      'alertsResolved': 45,
    },
  };
});

// Mock subscription info
final subscriptionProvider =
    StateProvider<String?>((ref) => null); // 'TRIAL' or 'PAID'
