// Generated by Copilot - TrackPose pages

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../services/frame_processor.dart';

// TODO: Add camera permissions to AndroidManifest.xml and Info.plist
// TODO: Initialize camera in initState with camera plugin

class LiveMonitoringScreen extends ConsumerStatefulWidget {
  const LiveMonitoringScreen({super.key});

  @override
  ConsumerState<LiveMonitoringScreen> createState() =>
      _LiveMonitoringScreenState();
}

class _LiveMonitoringScreenState extends ConsumerState<LiveMonitoringScreen> {
  late MockFrameProcessor _frameProcessor;
  late StreamController<FrameResult> _streamController;
  late Stream<FrameResult> _frameStream;

  @override
  void initState() {
    super.initState();
    _frameProcessor = MockFrameProcessor();
    _streamController = StreamController<FrameResult>();
    _frameStream = _streamController.stream;

    // Simulate frame processing every 2 seconds
    Timer.periodic(const Duration(seconds: 2), (timer) {
      if (!mounted) {
        timer.cancel();
        return;
      }
      final result = _frameProcessor.processSingleFrame();
      _streamController.add(result);
    });
  }

  @override
  void dispose() {
    _streamController.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Live Monitoring')),
      body: Column(
        children: [
          // Camera Preview Placeholder
          Expanded(
            child: Container(
              color: Colors.black,
              child: Stack(
                children: [
                  const Center(
                    child: Text(
                      'Camera Preview\n(TODO: Use camera plugin)',
                      textAlign: TextAlign.center,
                      style: TextStyle(color: Colors.white, fontSize: 16),
                    ),
                  ),
                  // Frame Result Overlay
                  Positioned(
                    bottom: 16,
                    left: 16,
                    right: 16,
                    child: StreamBuilder<FrameResult>(
                      stream: _frameStream,
                      builder: (context, snapshot) {
                        if (!snapshot.hasData) {
                          return const Card(
                            child: Padding(
                              padding: EdgeInsets.all(12.0),
                              child: Text('Waiting for frame data...'),
                            ),
                          );
                        }

                        final result = snapshot.data!;
                        final emotion =
                            result.emotionSummary['dominant'] as String;
                        final wellbeingScore = result.wellbeingScore;

                        return Card(
                          color: Colors.white.withValues(alpha: 0.9),
                          child: Padding(
                            padding: const EdgeInsets.all(12.0),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisSize: MainAxisSize.min,
                              children: [
                                const Text(
                                  'Live Analysis',
                                  style: TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                  ),
                                ),
                                const SizedBox(height: 8),
                                Text('Emotion: $emotion'),
                                const SizedBox(height: 4),
                                Text('Wellbeing Score: $wellbeingScore'),
                              ],
                            ),
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
          // Controls
          Container(
            padding: const EdgeInsets.all(16),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                ElevatedButton.icon(
                  onPressed: () {
                    // TODO: Implement capture
                  },
                  icon: const Icon(Icons.camera),
                  label: const Text('Capture'),
                ),
                OutlinedButton.icon(
                  onPressed: () {
                    Navigator.pop(context);
                  },
                  icon: const Icon(Icons.stop),
                  label: const Text('Stop'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
