// Generated by Copilot - TrackPose pages

import 'package:flutter/material.dart';

class ReportsAiInsightsScreen extends StatefulWidget {
  const ReportsAiInsightsScreen({super.key});

  @override
  State<ReportsAiInsightsScreen> createState() =>
      _ReportsAiInsightsScreenState();
}

class _ReportsAiInsightsScreenState extends State<ReportsAiInsightsScreen> {
  final List<InsightCategory> _categories = [
    InsightCategory(
      title: 'Emotional Wellbeing',
      insights: [
        'Child shows consistent positive engagement during morning activities',
        'Slight increase in frustration indicators during transition periods',
        'Strong emotional regulation observed during group play',
      ],
    ),
    InsightCategory(
      title: 'Social Interaction',
      insights: [
        'Prefers small group interactions (2-3 peers)',
        'Demonstrates leadership qualities during structured activities',
        'Increasing confidence in initiating peer interactions',
      ],
    ),
    InsightCategory(
      title: 'Physical Activity',
      insights: [
        'Active engagement in outdoor play for 45 minutes daily average',
        'Preference for running and climbing activities',
        'Adequate rest periods observed between high-energy activities',
      ],
    ),
    InsightCategory(
      title: 'Cognitive Development',
      insights: [
        'Sustained attention span of 15-20 minutes on preferred tasks',
        'Problem-solving skills improving with hands-on activities',
        'Shows curiosity and asks thoughtful questions',
      ],
    ),
    InsightCategory(
      title: 'Behavioral Patterns',
      insights: [
        'Consistent routine adherence with minimal resistance',
        'Responds well to positive reinforcement',
        'Self-regulation improving over observation period',
      ],
    ),
    InsightCategory(
      title: 'Environmental Factors',
      insights: [
        'Optimal engagement in well-lit, spacious areas',
        'Noise levels above 70dB correlate with decreased focus',
        'Natural light exposure linked to improved mood indicators',
      ],
    ),
    InsightCategory(
      title: 'Recommendations',
      insights: [
        'Continue current morning routine structure',
        'Introduce gradual transition warnings (5-minute notices)',
        'Maintain small group sizes for optimal social development',
        'Ensure outdoor play time remains consistent',
      ],
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('AI Insights & Reports')),
      body: SingleChildScrollView(
        child: ExpansionPanelList(
          expansionCallback: (panelIndex, isExpanded) {
            setState(() {
              _categories[panelIndex].isExpanded = !isExpanded;
            });
          },
          children: _categories.map<ExpansionPanel>((category) {
            return ExpansionPanel(
              headerBuilder: (context, isExpanded) {
                return ListTile(
                  title: Text(
                    category.title,
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                );
              },
              body: Padding(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: category.insights
                      .map((insight) => Padding(
                            padding: const EdgeInsets.symmetric(vertical: 4),
                            child: Text('• $insight'),
                          ))
                      .toList(),
                ),
              ),
              isExpanded: category.isExpanded,
            );
          }).toList(),
        ),
      ),
    );
  }
}

class InsightCategory {
  final String title;
  final List<String> insights;
  bool isExpanded;

  InsightCategory({
    required this.title,
    required this.insights,
    this.isExpanded = false,
  });
}
