// Generated by Copilot - TrackPose pages
// Updated with proper user flows

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'providers/auth_provider.dart';
import 'screens/intro_welcome_screen.dart';
import 'screens/onboarding_how_it_works_1.dart';
import 'screens/onboarding_how_it_works_2.dart';
import 'screens/onboarding_privacy.dart';
import 'screens/choose_role_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/login_screen.dart';
import 'screens/verification_screen.dart';
import 'screens/facility_choice_screen.dart';
import 'screens/choose_plan_screen.dart';
import 'screens/facility_setup_choice_screen.dart';
import 'screens/facility_setup_screen.dart';
import 'screens/home_facility_screen.dart';
import 'screens/external_facility_screen.dart';
import 'screens/caregiver_facility_setup_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/admin_dashboard_screen.dart';
import 'screens/parent_dashboard_screen.dart';
import 'screens/staff_dashboard_screen.dart';
import 'screens/forgot_password_screen.dart';
import 'screens/reset_password_screen.dart';
import 'screens/access_code_entry_screen.dart';

final routerProvider = Provider<GoRouter>((ref) {
  final authState = ref.watch(authProvider);

  return GoRouter(
    initialLocation: '/',
    redirect: (context, state) {
      final isAuthenticated = authState.isAuthenticated;
      final isEmailVerified = authState.isEmailVerified;
      final hasEmail = authState.email != null;
      final location = state.uri.toString();

      print('🔀 ROUTER: Checking redirect for: $location');
      print('   isAuthenticated: $isAuthenticated, hasEmail: $hasEmail, isVerified: $isEmailVerified');

      // Public routes that don't require authentication
      final publicRoutes = [
        '/',
        '/onboarding-1',
        '/onboarding-2',
        '/onboarding-privacy',
        '/choose-role',
        '/login',
        '/signup',
        '/forgot-password',
        '/reset-password',
        '/email-verification', // ADD THIS - Allow verification page access after signup
      ];
      final isPublicRoute =
          publicRoutes.any((route) => location.startsWith(route));

      print('   isPublicRoute: $isPublicRoute');

      // If not authenticated and trying to access protected route
      if (!isAuthenticated && !isPublicRoute) {
        print('   ❌ REDIRECT: Not authenticated, going to /login');
        return '/login';
      }
      
      // Block email verification if no email stored (direct access attempt)
      if (location == '/email-verification' && !hasEmail) {
        print('   ❌ REDIRECT: No email stored, going to /login');
        return '/login';
      }

      // If authenticated but email not verified (except for email-verification page)
      if (isAuthenticated &&
          !isEmailVerified &&
          location != '/email-verification') {
        print('   ⚠️ REDIRECT: Email not verified, going to /email-verification');
        return '/email-verification';
      }

      print('   ✅ REDIRECT: Allowing access to $location');
      // Allow access to all routes if authenticated and verified
      return null;
    },
    routes: [
      // Intro & Onboarding Flow (All users)
      GoRoute(
        path: '/',
        builder: (context, state) => const IntroWelcomeScreen(),
      ),
      GoRoute(
        path: '/onboarding-1',
        builder: (context, state) => const OnboardingHowItWorks1(),
      ),
      GoRoute(
        path: '/onboarding-2',
        builder: (context, state) => const OnboardingHowItWorks2(),
      ),
      GoRoute(
        path: '/onboarding-privacy',
        builder: (context, state) => const OnboardingPrivacy(),
      ),
      
      // Role Selection
      GoRoute(
        path: '/choose-role',
        builder: (context, state) => const ChooseRoleScreen(),
      ),

      // Auth Routes
      GoRoute(
        path: '/signup',
        builder: (context, state) {
          final role = state.uri.queryParameters['role'];
          return SignupScreen(role: role);
        },
      ),
      GoRoute(
        path: '/login',
        builder: (context, state) => const LoginScreen(),
      ),
      GoRoute(
        path: '/email-verification',
        builder: (context, state) => const VerificationScreen(),
      ),
      GoRoute(
        path: '/forgot-password',
        builder: (context, state) => const ForgotPasswordScreen(),
      ),
      GoRoute(
        path: '/reset-password',
        builder: (context, state) {
          final token = state.uri.queryParameters['token'];
          return ResetPasswordScreen(token: token);
        },
      ),

      // Parent/Family Flow Routes
      GoRoute(
        path: '/facility-choice',
        builder: (context, state) => const FacilityChoiceScreen(),
      ),
      GoRoute(
        path: '/choose-plan',
        builder: (context, state) => const ChoosePlanScreen(),
      ),
      GoRoute(
        path: '/facility-setup-choice',
        builder: (context, state) => const FacilitySetupChoiceScreen(),
      ),
      GoRoute(
        path: '/facility-setup',
        builder: (context, state) => const FacilitySetupScreen(),
      ),
      GoRoute(
        path: '/home-facility-setup',
        builder: (context, state) => const HomeFacilityScreen(),
      ),
      GoRoute(
        path: '/external-facility-setup',
        builder: (context, state) => const ExternalFacilityScreen(),
      ),
      GoRoute(
        path: '/access-code-entry',
        builder: (context, state) => const AccessCodeEntryScreen(),
      ),

      // Staff/Caregiver Flow Routes
      GoRoute(
        path: '/caregiver-facility-setup',
        builder: (context, state) => const CaregiverFacilitySetupScreen(),
      ),

      // Dashboard Routes
      GoRoute(
        path: '/dashboard',
        builder: (context, state) => const DashboardScreen(),
      ),
      GoRoute(
        path: '/admin-dashboard',
        builder: (context, state) => const AdminDashboardScreen(),
      ),
      GoRoute(
        path: '/parent-dashboard',
        builder: (context, state) => const ParentDashboardScreen(),
      ),
      GoRoute(
        path: '/staff-dashboard',
        builder: (context, state) => const StaffDashboardScreen(),
      ),
    ],
  );
});
