// Generated by Copilot - TrackPose pages

/// Application configuration constants
class AppConfig {
  // API Configuration
  static const String apiBaseUrl = 'https://api.trackpose.com'; // TODO: Replace with actual API URL
  static const String apiVersion = 'v1';
  
  // Stripe Configuration
  static const String stripePublishableKey = 'pk_test_YOUR_KEY_HERE'; // TODO: Set your Stripe key
  
  // Feature Flags
  static const bool enableDemoMode = true;
  static const bool enableAnalytics = false;
  
  // Timeout Configuration
  static const Duration apiTimeout = Duration(seconds: 30);
  static const Duration connectTimeout = Duration(seconds: 30);
  
  // Camera Configuration
  static const int maxVideoLength = 300; // seconds
  static const int frameProcessingInterval = 2; // seconds
  
  // Storage Keys
  static const String authTokenKey = 'auth_token';
  static const String userEmailKey = 'user_email';
  static const String userRoleKey = 'user_role';
  static const String emailVerifiedKey = 'email_verified';
  static const String facilityIdKey = 'facility_id';
  
  // Environment Detection
  static bool get isProduction => apiBaseUrl.contains('api.trackpose.com');
  static bool get isDevelopment => !isProduction;
}
