// Generated by Copilot - TrackPose pages

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/api_client_provider.dart';
import '../providers/auth_provider.dart';

class AccessCodeEntryScreen extends ConsumerStatefulWidget {
  const AccessCodeEntryScreen({super.key});

  @override
  ConsumerState<AccessCodeEntryScreen> createState() =>
      _AccessCodeEntryScreenState();
}

class _AccessCodeEntryScreenState extends ConsumerState<AccessCodeEntryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _codeCtrl = TextEditingController();
  bool _loading = false;

  @override
  void dispose() {
    _codeCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _loading = true);
    try {
      final apiClient = ref.read(apiClientProvider);
      // TODO: Get facility ID from auth state or API
      await apiClient.verifyAccessCode(
          'facility_id_placeholder', _codeCtrl.text.trim());

      if (!mounted) return;

      // Navigate to role-adaptive dashboard
      final role = ref.read(authProvider).role ?? 'PARENT';
      if (role == 'ADMIN' || role == 'MANAGER') {
        context.go('/admin-dashboard');
      } else if (role == 'STAFF' || role == 'CAREGIVER') {
        context.go('/staff-dashboard');
      } else {
        context.go('/parent-dashboard');
      }
    } catch (e) {
      if (!mounted) return;
      setState(() => _loading = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Invalid code: ${e.toString()}')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Access Code')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text(
                'Enter the access code sent to your verified email address.',
                style: TextStyle(fontSize: 16),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 32),
              TextFormField(
                controller: _codeCtrl,
                decoration: const InputDecoration(
                  labelText: 'Access Code',
                  border: OutlineInputBorder(),
                ),
                validator: (v) =>
                    v == null || v.isEmpty ? 'Enter access code' : null,
              ),
              const SizedBox(height: 24),
              _loading
                  ? const Center(child: CircularProgressIndicator())
                  : ElevatedButton(
                      onPressed: _submit,
                      child: const Padding(
                        padding: EdgeInsets.symmetric(vertical: 12),
                        child: Text('Submit'),
                      ),
                    ),
            ],
          ),
        ),
      ),
    );
  }
}
