// Generated by Copilot - TrackPose pages

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../providers/auth_provider.dart';
import '../providers/api_client_provider.dart';
import 'dart:math' as math;

class FacilitySetupScreen extends ConsumerStatefulWidget {
  const FacilitySetupScreen({super.key});

  @override
  ConsumerState<FacilitySetupScreen> createState() =>
      _FacilitySetupScreenState();
}

class _FacilitySetupScreenState extends ConsumerState<FacilitySetupScreen>
    with TickerProviderStateMixin {
  final _formKey = GlobalKey<FormState>();
  final _nameCtrl = TextEditingController();
  String _selectedType = 'school';
  bool _loading = false;
  late AnimationController _fadeController;
  late AnimationController _slideController;

  @override
  void initState() {
    super.initState();
    _fadeController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 600),
    )..forward();

    _slideController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 800),
    )..forward();
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _fadeController.dispose();
    _slideController.dispose();
    super.dispose();
  }

  bool _canSelectOwnHome() {
    final role = ref.read(authProvider).role;
    return role == 'PARENT' || role == 'ADMIN';
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    // Enforce own_home restriction
    if (_selectedType == 'own_home' && !_canSelectOwnHome()) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text(
              'Own home is only available for Parents/Family or Admin roles'),
          backgroundColor: Color(0xFFFF2E7A),
        ),
      );
      return;
    }

    setState(() => _loading = true);
    try {
      final apiClient = ref.read(apiClientProvider);
      await apiClient.createFacility(
        name: _nameCtrl.text.trim(),
        type: _selectedType,
      );
      if (!mounted) return;
      context.go('/plan-selection');
    } catch (e) {
      if (!mounted) return;
      setState(() => _loading = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Error: ${e.toString()}'),
          backgroundColor: Color(0xFFFF2E7A),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final size = MediaQuery.of(context).size;
    final contentWidth = math.min(size.width - 40, 500.0);

    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            colors: [
              Color(0xFF7A3FF2), // Purple
              Color(0xFFFF2E7A), // Pink
            ],
          ),
        ),
        child: SafeArea(
          child: Center(
            child: SingleChildScrollView(
              child: Padding(
                padding: const EdgeInsets.all(20.0),
                child: ConstrainedBox(
                  constraints: BoxConstraints(maxWidth: contentWidth),
                  child: FadeTransition(
                    opacity: _fadeController,
                    child: SlideTransition(
                      position: Tween<Offset>(
                        begin: const Offset(0, 0.1),
                        end: Offset.zero,
                      ).animate(CurvedAnimation(
                        parent: _slideController,
                        curve: Curves.easeOut,
                      )),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          // Icon with glow effect
                          TweenAnimationBuilder<double>(
                            tween: Tween(begin: 0.0, end: 1.0),
                            duration: const Duration(milliseconds: 1000),
                            builder: (context, value, child) {
                              return Container(
                                width: 120,
                                height: 120,
                                decoration: BoxDecoration(
                                  shape: BoxShape.circle,
                                  gradient: LinearGradient(
                                    colors: [
                                      Color(0xFF7A3FF2).withValues(alpha: 0.8),
                                      Color(0xFFFF2E7A).withValues(alpha: 0.8),
                                    ],
                                  ),
                                  boxShadow: [
                                    BoxShadow(
                                      color: Color(0xFF7A3FF2).withValues(alpha: 0.4 * value),
                                      blurRadius: 40 * value,
                                      spreadRadius: 10 * value,
                                    ),
                                  ],
                                ),
                                child: const Icon(
                                  Icons.business,
                                  size: 60,
                                  color: Colors.white,
                                ),
                              );
                            },
                          ),
                          const SizedBox(height: 32),
                          // Title
                          const Text(
                            'Set up your facility',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 32,
                              fontWeight: FontWeight.bold,
                              color: Colors.white,
                            ),
                          ),
                          const SizedBox(height: 12),
                          const Text(
                            'Configure your facility details',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              fontSize: 16,
                              color: Colors.white70,
                            ),
                          ),
                          const SizedBox(height: 40),
                          // White card
                          Container(
                            padding: const EdgeInsets.all(28.0),
                            decoration: BoxDecoration(
                              color: Colors.white,
                              borderRadius: BorderRadius.circular(24),
                              boxShadow: [
                                BoxShadow(
                                  color: Colors.black.withValues(alpha: 0.1),
                                  blurRadius: 20,
                                  offset: const Offset(0, 10),
                                ),
                              ],
                            ),
                            child: Form(
                              key: _formKey,
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.stretch,
                                children: [
                                  // Facility Name Input
                                  TextFormField(
                                    controller: _nameCtrl,
                                    style: const TextStyle(fontSize: 16),
                                    decoration: InputDecoration(
                                      labelText: 'Facility Name',
                                      labelStyle: const TextStyle(
                                        color: Color(0xFF6B7280),
                                        fontSize: 14,
                                      ),
                                      filled: true,
                                      fillColor: const Color(0xFFF3F4F6),
                                      border: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: BorderSide.none,
                                      ),
                                      enabledBorder: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: BorderSide.none,
                                      ),
                                      focusedBorder: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: const BorderSide(
                                          color: Color(0xFF7A3FF2),
                                          width: 2,
                                        ),
                                      ),
                                      contentPadding: const EdgeInsets.symmetric(
                                        horizontal: 20,
                                        vertical: 18,
                                      ),
                                    ),
                                    validator: (v) => v == null || v.isEmpty
                                        ? 'Enter facility name'
                                        : null,
                                  ),
                                  const SizedBox(height: 20),
                                  // Facility Type Dropdown
                                  DropdownButtonFormField<String>(
                                    value: _selectedType,
                                    style: const TextStyle(
                                      fontSize: 16,
                                      color: Color(0xFF0F1724),
                                    ),
                                    decoration: InputDecoration(
                                      labelText: 'Facility Type',
                                      labelStyle: const TextStyle(
                                        color: Color(0xFF6B7280),
                                        fontSize: 14,
                                      ),
                                      filled: true,
                                      fillColor: const Color(0xFFF3F4F6),
                                      border: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: BorderSide.none,
                                      ),
                                      enabledBorder: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: BorderSide.none,
                                      ),
                                      focusedBorder: OutlineInputBorder(
                                        borderRadius: BorderRadius.circular(14),
                                        borderSide: const BorderSide(
                                          color: Color(0xFF7A3FF2),
                                          width: 2,
                                        ),
                                      ),
                                      contentPadding: const EdgeInsets.symmetric(
                                        horizontal: 20,
                                        vertical: 18,
                                      ),
                                    ),
                                    items: const [
                                      DropdownMenuItem(
                                          value: 'school', child: Text('School')),
                                      DropdownMenuItem(
                                          value: 'care_home',
                                          child: Text('Care Home')),
                                      DropdownMenuItem(
                                          value: 'assisted_living',
                                          child: Text('Assisted Living')),
                                      DropdownMenuItem(
                                          value: 'childcare_center',
                                          child: Text('Childcare Center')),
                                      DropdownMenuItem(
                                          value: 'play_center',
                                          child: Text('Play Center')),
                                      DropdownMenuItem(
                                          value: 'own_home',
                                          child: Text(
                                              'Own Home (Parents/Family or Admin only)')),
                                    ],
                                    onChanged: (value) {
                                      setState(() {
                                        _selectedType = value ?? 'school';
                                      });
                                    },
                                  ),
                                  const SizedBox(height: 32),
                                  // Submit Button
                                  _loading
                                      ? Center(
                                          child: Container(
                                            width: 50,
                                            height: 50,
                                            padding: const EdgeInsets.all(12),
                                            decoration: BoxDecoration(
                                              gradient: const LinearGradient(
                                                colors: [
                                                  Color(0xFF7A3FF2),
                                                  Color(0xFFFF2E7A),
                                                ],
                                              ),
                                              borderRadius:
                                                  BorderRadius.circular(25),
                                            ),
                                            child: const CircularProgressIndicator(
                                              strokeWidth: 3,
                                              valueColor:
                                                  AlwaysStoppedAnimation<Color>(
                                                      Colors.white),
                                            ),
                                          ),
                                        )
                                      : Material(
                                          color: Colors.transparent,
                                          child: InkWell(
                                            onTap: _submit,
                                            borderRadius:
                                                BorderRadius.circular(28),
                                            child: Ink(
                                              decoration: BoxDecoration(
                                                gradient: const LinearGradient(
                                                  colors: [
                                                    Color(0xFF7A3FF2),
                                                    Color(0xFFFF2E7A),
                                                  ],
                                                ),
                                                borderRadius:
                                                    BorderRadius.circular(28),
                                                boxShadow: [
                                                  BoxShadow(
                                                    color: const Color(0xFF7A3FF2)
                                                        .withValues(alpha: 0.4),
                                                    blurRadius: 20,
                                                    offset: const Offset(0, 10),
                                                  ),
                                                ],
                                              ),
                                              child: Container(
                                                height: 56,
                                                alignment: Alignment.center,
                                                child: const Text(
                                                  'Continue',
                                                  style: TextStyle(
                                                    fontSize: 18,
                                                    fontWeight: FontWeight.w600,
                                                    color: Colors.white,
                                                  ),
                                                ),
                                              ),
                                            ),
                                          ),
                                        ),
                                ],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
