// Generated by Copilot - TrackPose pages

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

class PaymentScreen extends ConsumerWidget {
  const PaymentScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: const Text('Payment')),
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Text('Payment Screen'),
              const SizedBox(height: 24),
              ElevatedButton(
                onPressed: () => context.go('/access-code-entry'),
                child: const Text('Complete Payment'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
