// Generated by Copilot - TrackPose pages

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class ProfileDetailScreen extends ConsumerWidget {
  final Map<String, dynamic> profile;

  const ProfileDetailScreen({super.key, required this.profile});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      appBar: AppBar(title: Text(profile['name'] ?? 'Profile')),
      body: const Center(child: Text('Profile Detail Screen')),
    );
  }
}
