import express from 'express';
import cors from 'cors';
import authRoutes from './routes/auth';
import sessionsRoutes from './routes/sessions';
const app = express();
app.use(cors()); app.use(express.json());
app.use('/api/v1/auth', authRoutes);
app.use('/api/v1/sessions', sessionsRoutes);
app.get('/api/v1/admin/system-health',(req,res)=>res.json({ok:true}));
export default app;
